# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.


test:
  secret_key_base: 038f58a42022a72a809e499f94355afb213f28dbdff60a37cfc66bfbd2910934345ea235da37bcf009940737fc8b429238043cfbbbb011e58ee9659c0558866b
  s3_access_key_id: 'fake-access-key-id'
  s3_secret_access_key: 'fake-secret-access-key'
  s3_bucket: 'fake-aws-s3-bucket'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production: &production
  secret_key_base: ENV["SECRET_KEY_BASE"]
  s3_access_key_id: ENV['AWS_ACCESS_KEY_ID']
  s3_secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
  s3_bucket: ENV['AWS_S3_BUCKET']

development:
  <<: *production

staging:
  <<: *production

